language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: bot@strajah.com
  api_key:
    secure: kf+k28R+ntm5mMxIcvkEBpvk1Li+KOTA/4IokDn6eRjGlOolgFbmiCm1hdqRS6KIyoll5TyzCX6xHnCumhRWAeTrty11XrjFhJc0IR+lX0T4yX7LrvMDmFjYMKQKQyIHsWaHWyOkILHpq8stbhcKfJ3iVlenrLfisd3LrlLlgMw=
  on:
    tags: true
    repo: strajah/strajah
    all_branches: true

after_success:
  # CREATE GIT TAG
  - git config --global user.email "bot@strajah.com"
  - git config --global user.name "Strajah Bot"
  - export GIT_TAG=b$TRAVIS_BUILD_NUMBER
  - echo -n $GIT_TAG > public/version
  - git commit -m "Set build VERSION number" public/version
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUBKEY@github.com/strajah/strajah.git $GIT_TAG > /dev/null 2>&1