language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: bot@strajah.com
  api_key:
    secure: kf+k28R+ntm5mMxIcvkEBpvk1Li+KOTA/4IokDn6eRjGlOolgFbmiCm1hdqRS6KIyoll5TyzCX6xHnCumhRWAeTrty11XrjFhJc0IR+lX0T4yX7LrvMDmFjYMKQKQyIHsWaHWyOkILHpq8stbhcKfJ3iVlenrLfisd3LrlLlgMw=
  on:
    tags: true
    repo: strajah/strajah
    all_branches: true
